### ISSUE TITLE
施設データの投入が出来なくなっている

### ISSUE THREAD

**Issue by rod91** [yoshitokamizato/go-to-nago#121]
## 概要
ImportCsv.import('db/csv_data/facility_data.csv')

```
NoMethodError: undefined method `created_id' for #<Facility:0x00007fbb04e7e480>
Did you mean?  created_at
               created_at?
               created_at=
```

## タスク

- [ ] インポートできるようにする
- [ ] インポートできなくなった原因

**Comment by great084** [comment]
【原因】
以下の対応で、facility modelにvalidates追加しているが、タイプミスが原因。(正:created_user,  誤:created_id)
https://github.com/yoshitokamizato/go-to-nago/pull/110/files
