### ISSUE TITLE
観光施設一覧で観光施設が正常に取得できていない

### ISSUE THREAD

**Issue by rod91** [yoshitokamizato/go-to-nago#122]
https://github.com/yoshitokamizato/go-to-nago/blob/8db0b12c778163c8e0259a95d2fd787287cb0592/app/controllers/facilities_controller.rb#L4

facilities というenumは定義されていないので、意図しないデータが取得されています。
あと、設計レビュー時も指摘しましたが、タイプはグルメとスポットです。

**Comment by MinoruKotegawa** [comment]
以下の方針で修正。

facility.rbのenum値
enum type:{facility: 0,gourmet:1}
を
enum type:{spot: 0,gourmet:1}
に修正。
2. システム内のfacilityのtypeのenum値を使用している箇所の「facility」及び「facilities」を「spot」に修正。
