### ISSUE TITLE
掲載情報の登録/修正依頼の機能

### ISSUE THREAD

**Issue by great084** [yoshitokamizato/go-to-nago#128]
## 概要

店舗、観光施設情報の、登録/修正を依頼する機能を作成する
問い合わせ機能を利用して、一部用途に応じたUI,項目設計を行う。

## タスク

- [x] 画面設計

画面項目の設定内容
問合せ画面への遷移経路によって、「題名」「お問合せ内容」などの表示内容を設定する。
![image](https://user-images.githubusercontent.com/36526480/88460580-35daa200-ced8-11ea-970a-198f0447779d.png)

- [x] 実装

## 設計資料
https://docs.google.com/spreadsheets/d/1_3LaIt6jBby83_2I85Cp1gvjrchuJfHb-J0iNNA4dds/edit#gid=0

**Comment by great084** [comment]
@rod91 
情報掲載依頼、修正依頼の問合せフォームの画面項目表示内容を上にまとめましたので、ご確認いただけますでしょうか？
基本的には、問合せ画面への遷移経路によって、「題名」「お問合せ内容」などの表示内容を設定する方針としています。

【質問】
・「情報掲載依頼」の場合、一回の掲載依頼ですべての店舗情報を受け付けるのではなく、あくまで掲載の手続きのきっかけであり、Webページで表示するすべての情報（ex駐車場、メニューなど）は記入する必要ないと考えていますが、いかがでしょうか？

・「情報削除依頼」はUCには記載ありましたが、ワイヤーフレームには導線がありませんでした。明示的な機能として必要でしょうか？
（ざっくばらんな、「お問合せ」から受け付けるとしてもよいのかなと思いました）

**Comment by rod91** [comment]
ありがとうございます。
方針良いと思います。

> ・「情報掲載依頼」の場合、一回の掲載依頼ですべての店舗情報を受け付けるのではなく、あくまで掲載の手続きのきっかけ> であり、Webページで表示するすべての情報（ex駐車場、メニューなど）は記入する必要ないと考えていますが、いかがでし> ょうか？
→ 当初は問い合わせ件数も少ないと思いますし、写真などは別途やりとりが必要なので連絡先と施設名は必須、それ以外は一旦外しでもいいと思います。
住所、URLくらいは任意でいれてもらえると良いかもですね。

> ・「情報削除依頼」はUCには記載ありましたが、ワイヤーフレームには導線がありませんでした。明示的な機能として必要> でしょうか？
> （ざっくばらんな、「お問合せ」から受け付けるとしてもよいのかなと思いました）
 → 修正依頼で『削除してください』っていう依頼が放っておいても来ると思うので、明示的に『削除依頼』という機能はなくてもいいと思います。（できれば情報消したくないし）

**Comment by rod91** [comment]
あと、修正依頼の場合、裏で対象の施設IDも保存できるようにしておくといいと思います。

**Comment by great084** [comment]
了解しました。
登録依頼は主要な情報を入力してもらえるようにして、削除依頼はなしで進めます。
確かに修正依頼の場合は施設idもセットできるといいので、DB保存できる良いにします!
