### ISSUE TITLE
画面の調整（TOP及び、全画面共通部分）

### ISSUE THREAD

**Issue by rod91** [yoshitokamizato/go-to-nago#133]
## 概要
トンマナを作成したのでTOPと全体共通部分に充てていってください。

カラーコード
基本色 ： #3D85C6
テキスト 黒： #000000
テキスト グレー： #7C7B7B
テキスト 白 ： #FFFFFF
テキスト 赤 ： #FF0000
グラデーションボタン ： #353D24 #55ACEE
 → #88B920 #55ACEE かも。

素材
https://drive.google.com/drive/u/0/folders/1Jb520Fr5wqfc5ZVwHcsI15cGGXipdt2k

## タスク
- [x] 全体共通部分のスタイル適用（ヘッダー、フッダー、見出し、テキスト、ボタン）
- [x] TOPページ

**Comment by great084** [comment]
@rod91 
> グラデーションボタン ： #353D24 #55ACEE
グラデーションカラーの"#353D24"って、正しいでしょうか？
上記カラーでボタン作成したんですが、左側の色がデザインサンプルと大きく変わってしまいます。
![image](https://user-images.githubusercontent.com/36526480/89094524-b7ae5c00-d3ff-11ea-95a9-f5c45de1a760.png)

**Comment by rod91** [comment]
描画ツールのエフェクトに掛け方によるみたいです。
#88B920

これでどうですか？

**Comment by great084** [comment]
ありがとうございます！
いい感じの色になりました。

![image](https://user-images.githubusercontent.com/36526480/89098311-61521500-d421-11ea-9e10-92d77f285b6e.png)

**Comment by rod91** [comment]
よかったっすー。
他の画面を作ったら、デザインツールごと共有しますねー。

**Comment by great084** [comment]
了解しました〜

**Comment by rod91** [comment]
これで本物のサービスっぽくなりますねー！
他ページ書かねば！
