### ISSUE TITLE
画面の調整（施設一覧）

### ISSUE THREAD

**Issue by rod91** [yoshitokamizato/go-to-nago#134]
## 概要

グルメと観光スポットの一覧にデザインをあてていってください。
トンマナはこちら

https://github.com/yoshitokamizato/go-to-nago/wiki/Design

**Comment by great084** [comment]
@rod91 
グルメと観光スポットの一覧にデザイン適用してみました。
以下の点、確認させてください。
- パンくずリストはとりあえず、元々表示されている内容を引き継いでいますがデザイン案ありますでしょうか？
- topページ同様に、スマホで2列、PCで4列表示としています。
- 背景もtopページ同様に、グルメはなし、観光スポットは背景画像を差し込んでいます。


グルメ | 観光スポット
---- | ----
<img src="https://user-images.githubusercontent.com/36526480/90305373-e4cd3500-defc-11ea-88f9-eec87ba7899d.png" width="320"/> | <img src="https://user-images.githubusercontent.com/36526480/90305376-e7c82580-defc-11ea-8c36-1f451bb2e3ab.png" width="320"/>
