### ISSUE TITLE
ユーザーの誕生年はdatetimeでなくてintで良い

### ISSUE THREAD

**Issue by rod91** [yoshitokamizato/go-to-nago#150]
## 概要

誕生年がdatetimeになっていますが、intでいいと思います。

## タスク

- [ ] 仕様書修正
- [ ] 影響範囲洗い出し
- [ ] 改修

**Comment by nobuosan** [comment]
これに付随して、誕生年が空っぽの時（何も登録されていない場合）datatimeの部分でエラーが起きています
