### ISSUE TITLE
営業時間に実日付が表示されている

### ISSUE THREAD

**Issue by great084** [yoshitokamizato/go-to-nago#154]
## 概要

- 現状：営業時間に実日付が表示されている
- あるべき姿：曜日ごとに時間が表示されるべき
<img src="https://user-images.githubusercontent.com/36526480/88484148-a1d80b80-cfa7-11ea-8f99-e3839105ac3b.png" width="500px">

## タスク

- [ ] 項目1
- [ ] 項目2
- [ ] 項目3

**Comment by rod91** [comment]
一旦String型に変換して対応、検索機能などを付ける際に再設計しましょう。
