### ISSUE TITLE
iPhoneでサイトを見るとボタンが崩れている

### ISSUE THREAD

**Issue by rod91** [yoshitokamizato/go-to-nago#171]
## 概要
iPhone でサイトを見るとボタンのスタイルが崩れています。
iPhone11 iOS 13 Safari です。

![iOS の画像](https://user-images.githubusercontent.com/9865774/90090901-2379b880-dd60-11ea-8d6b-8bc4bff38b71.png)

## タスク

- [x] 実機確認
- [x] 原因調査
- [x] 対応

**Comment by great084** [comment]
Android OS(Chrome)でも同様にボタンが崩れていました。
調べてみると、webkit系のモバイル用ブラウザ（Safari、Android標準、Android Chrome）では、CSSの指定を無視してデフォルトスタイルのままになる現象（バグ？）があるとのこと。
解消するには、CSSで`-webkit-appearance: none;`を指定すると解消できる模様。
