### ISSUE TITLE
仮登録時のメールのタイトルが「【名護へGO】会員登録完了」になっている。

### ISSUE THREAD

**Issue by great084** [yoshitokamizato/go-to-nago#241]
## 概要

仮登録時のメールのタイトルが、会員登録完了していないにもかかわらず、
「【名護へGO】会員登録完了」になっている。

## タスク

- [ ] 項目1
- [ ] 項目2
- [ ] 項目3

**Comment by MinoruKotegawa** [comment]
@great084 
こちらの現象ですが、「仮登録メールの修正(https://github.com/yoshitokamizato/go-to-nago/commit/33fe086ce2abf9e1f6b7a0d077b4ab26fb5618e6#diff-de4f821585c5718c774128e10845a2f6)」にて修正済みです。(masterにもマージ済)
お手数お掛け致しますが内容確認の上、修正されていることが確認出来ましたらクローズをお願い致します。

**Comment by great084** [comment]
@MinoruKotegawa 

確認しました。直近のdevelopをfetchしてませんでた〜
対応済みなので、クローズします。
