### ISSUE TITLE
画面の調整（追加分）（共通＆トップ）

### ISSUE THREAD

**Issue by great084** [yoshitokamizato/go-to-nago#249]
## 概要

TOP & 全体共通
- [x] スマホのメニューをクリックしたときに右上の〇アイコンが一瞬消えるのが気になる
- [x] メインロゴはH1で囲った方が良いです。
- [x] おすすめグルメ などの見出しはもう少し小さくしましょう。ロゴより大きいので1.2remくらいでよいです。
- [x] ページのTOPからセクションのまでのスペースは40pxくらいで良いです。（今は100px）タイトルとコンテンツのマージンも15px程でいいですかね。
- [x] H4は1remで良いのと、.card-text は0.8サイズもremくらい、♡のサイズも併せて小さくしたいけど、その分数字の場所もクリックできるようにして領域を広げたほうが良いです。
- [x] おすすめグルメをもっと見るのボタンはセクション幅と併せて大きく、ボタンのテキストはここはも少し大きくていいです。
→ その他全体的にパーツは上記に合わせる
- [x] フッターの罫線がtopとbttomが被って2pxになっているので、どちらか1本を引けばよいです。
- [x] PCのとのヘッダーがコンテンツ幅で切れているので、ヘッダー自体は全幅でおねがいします。
- [x] おすすめスポットの背景はかのであれば全幅にしたいです。 → 対応不要とする

**Comment by great084** [comment]
@rod91 
>  メインロゴはH1で囲った方が良いです。

h1タグは各ページの見出しの位置づけの認識なので、メインロゴをh1タグで囲うと全ページ見出しが同じなっていしまいます。
現在、<h3>タグで記載されている、「おすすめグルメ」などのタイトルをh1タグに変更するのではどうでしょうか？

**Comment by great084** [comment]
現状、パンくずリストのありなしのページが混在しています。
名護へGOは、ページ構成・数ともシンプルなので、
ないほうがデザイン的にスッキリして良いかなと思いましたがいかがでしょうか？

**Comment by great084** [comment]
> おすすめスポットの背景はかのであれば全幅にしたいです。
htmlのタグ構成を大幅に変えなくてはいけないため、対応見送りでも良いでしょうか？

**Comment by great084** [comment]
フォントは、Google web fontのNoto Sans JPを適用でよいでしょうか？

**Comment by rod91** [comment]
質問かえしたつもりが投稿で来てなかったっぽい💦

> 1タグは各ページの見出しの位置づけの認識なので、メインロゴをh1タグで囲うと全ページ見出しが同じなっていしまいま
> す。現在、h3タグで記載されている、「おすすめグルメ」などのタイトルをh1タグに変更するのではどうでしょうか？

『名護のおすすめスポット』 とかになっていれば大丈夫です。
良くやるのはTOPはロゴのALTで指定、詳細のページは店名などの部分をh1に使います。

> 現状、パンくずリストのありなしのページが混在しています。
> 名護へGOは、ページ構成・数ともシンプルなので、
> ないほうがデザイン的にスッキリして良いかなと思いましたがいかがでしょうか？

各ページに戻るボタンが付いていればそれでよいですよ、あとサイトマップを作りましょう。
戻るボタンというのはメニュー一覧からグルメ詳細にもどるボタンという事です。

> htmlのタグ構成を大幅に変えなくてはいけないため、対応見送りでも良いでしょうか？

OKです。

> フォントは、Google web fontのNoto Sans JPを適用でよいでしょうか？

そうですね、日本語だと一番きれいだと思います。

**Comment by great084** [comment]
@rod91 
回答ありがとうございます。

> 『名護のおすすめスポット』 とかになっていれば大丈夫です。
良くやるのはTOPはロゴのALTで指定、詳細のページは店名などの部分をh1に使います。

ロゴはALT設定とし、現状のh3タグで指定されたタイトルをh1タグに変更します。

> 各ページに戻るボタンが付いていればそれでよいですよ、あとサイトマップを作りましょう。
戻るボタンというのはメニュー一覧からグルメ詳細にもどるボタンという事です。

「戻る」オペレーションを考えると、やはりパンくずリストあったほうが良いですね。
サイトマップ作成も了解です。


>> フォントは、Google web fontのNoto Sans JPを適用でよいでしょうか？

> そうですね、日本語だと一番きれいだと思います。

了解しました。Noto Sans JPを適用します。
