### ISSUE TITLE
店舗のURLにリンク設定をつける

### ISSUE THREAD

**Issue by great084** [yoshitokamizato/go-to-nago#285]
## 概要

施設情報に表示されるURLにリンク設定をつけたい

![image](https://user-images.githubusercontent.com/36526480/101038171-da739b80-35be-11eb-9816-e622faaa0901.png)

## タスク

- [ ] 項目1
- [ ] 項目2
- [ ] 項目3

**Comment by MinoruKotegawa** [comment]
#296 と同件のため、こちらはクローズする。
