### ISSUE TITLE
各種画像を用意して設定する

### ISSUE THREAD

**Issue by rod91** [yoshitokamizato/go-to-nago#291]
## 概要

店舗の画像、TOP画像、名護へGOとはの画像

## タスク

- [ ] 項目1
- [ ] 項目2
- [ ] 項目3

**Comment by rod91** [comment]
![IMG_1851](https://user-images.githubusercontent.com/9865774/104150294-ca03db80-541c-11eb-89c2-682c1806f036.jpg)

こちらの画像をTOPに設置して（画像のトリミングとかはしてください）、テキストで以下の様に設置してください。

ーーー
**羽地で一息、ついていきませんか？**

名護へGOは羽地の魅力的なお店やスポットをご紹介しています。
ーーー

**Comment by rod91** [comment]
https://go-to-nago.com/about

は、TOPに以下の写真を設置して、残りの写真は削除でお願いします。
他に良さげな素材が来たら設置しますがいまのところはこの景色写真だけなので。


![IMG_1860](https://user-images.githubusercontent.com/9865774/104150638-dd637680-541d-11eb-9b75-350b920a13a2.jpg)

**Comment by MinoruKotegawa** [comment]
@rod91 @great084 @nobuosan @yuukou3333 

「名護へGoについて」のページの修正を行いました。
https://github.com/yoshitokamizato/go-to-nago/pull/324

お手数お掛け致しますが、内容の確認をお願い致します。

**Comment by rod91** [comment]
羽地で一息、ついていきませんか？

![IMG_0631](https://user-images.githubusercontent.com/9865774/104793956-2a619700-57e8-11eb-87ac-424eee799811.JPG)

那覇から車で約1時間半の所に名護市羽地地区はあります。

美味しい食事処と豊かな自然に囲まれた美しい所です。
![IMG_1851](https://user-images.githubusercontent.com/9865774/104793990-4feea080-57e8-11eb-8641-8d0e0b69b479.jpg)


近所に「沖縄美ら海水族館」や「古宇利大橋」もあるため、観光客も足を運びやすい場所にあります。


「名護へGo」ではここ羽地地区を中心に、美味しい食事処や遊べる施設について紹介していきます。
![IMG_0159](https://user-images.githubusercontent.com/9865774/104794005-6137ad00-57e8-11eb-8394-ca3273383749.jpg)


突き抜けるような青い空と
どこまでも透き通る青い海
そして美味しいお食事を用意して

皆さまをお待ちしております。

**Comment by rod91** [comment]
画像はりました！
最終系これで行きましょう！

**Comment by rod91** [comment]
あ、ついかですみません。

`「名護へGo」ではここ羽地地区を中心に、美味しい食事処や遊べる施設について紹介していきます。
`

名護へGO 

にしましょうか。
Oを大文字に。
