### ISSUE TITLE
一覧実装(グルメ店舗,観光スポット)

### ISSUE THREAD

**Issue by rod91** [yoshitokamizato/go-to-nago#6]

**Comment by nobuosan** [comment]
//memo
開発のために、uesr.rbの
____________________________________________
  validates :nickname, presence: false
  validates :birth_year, presence: false
  validates :prefecture, presence: false
____________________________________________
を以下に変更push時に変更する
____________________________________________
  validates :nickname, presence: true
  validates :birth_year, presence: true
  validates :prefecture, presence: true
____________________________________________
