### ISSUE TITLE
メニューが設定されていないとエラーになる

### ISSUE THREAD

**Issue by rod91** [yoshitokamizato/go-to-nago#87]
## 概要

/facilities/5

にアクセスするとエラーになります。

```
/app/views/facilities/show.html.erb where line #65 raised:
undefined method `image' for nil:NilClass

          <%= image_tag("/menu_image/"+@facility.menus[0].image ,class:"d-block w-100" ,alt:"...") %>
```

## タスク
メニューデータがないとエラーになるようです。
メニューが無くてもサイト自体は表示できるようにしてください。

**Comment by MinoruKotegawa** [comment]
以下の方針で修正。

・メニューなし
メニュー欄ごと非表示

・メニュー1件
メニュー画像表示
メニュースライドカーソル「<」「>」非表示
インジケーター非表示
「もっと見る」ボタン表示

・メニュー2件以降
メニュー画像表示
メニュースライドカーソル「<」「>」表示
インジケーター表示
「もっと見る」ボタン表示
