### ISSUE TITLE
問い合わせページ

### ISSUE THREAD

**Issue by rod91** [yoshitokamizato/go-to-nago#93]
## 概要
問い合わせページを作成してください。
まずは項目は、問合せ主名、メールアドレス、問合せ内容 を投稿できるようにしましょう。
ログインしていたらそのIDもわかるほうが良いです。

※GEMなのでできればそれでも良いです。使用するGEMを提案してください。

## タスク
- [x] 参考サイトをピックアップ
- [x] 画面設計、データ設計
- [x] ページ作成
- [x] ~~メール送信（開発環境)~~ 
- [x] ~~管理者画面での表示・ステータス更新~~
- [x] ~~メール送信（本番環境）~~

**Comment by great084** [comment]
## 参考サイト
[マチログ](https://machi-log.net/?page_id=42779) →シンプルな問い合わせページ
[reallocal](https://www.reallocal.jp/ad)→情報掲載依頼のページ

## 機能設計
問い合わせ内容は、画面から入力する。確認画面を経て送信する。
送信した内容はDBに蓄積するとともに、リアルタイムで管理者へメールを送信する。
ログイン/非ログインに関わらず利用可能とする。（ログインしていた場合はIDも連携される）
### 画面設計
### データ設計
#### 問い合わせ種類
- 店舗/施設掲載依頼
- 店舗/施設情報 修正依頼  ※ログイン状態のみ
- その他問い合わせ

**Comment by rod91** [comment]
仕様良いです！
DBにはinquiriesのユニークキー（問い合わせ番号）と、投稿日時（今後のことも考えて更新日時）も入れてください。
とりあえずそれでいいです。

将来的には対応のステータスとかがメモできると問合せ担当はありがたいですね。

**Comment by great084** [comment]
DB設計に以下の項目を追加。
- id （自動追加）
- 問い合わせステータス
- タイムスタンプ（自動追加）

**Comment by great084** [comment]
タスクのボリュームが大きくなりすぎたため、以下のタスクは、新しいissueに設定して外だし。
- メール送信（開発環境）
- 管理者画面での表示・ステータス更新
- メール送信（本番環境）
